### PR TITLE
Some more code improvements

### PR DESCRIPTION
**Pull request by natewind**
Please build before merging. It should be ok, but I haven’t tried, since I still don’t have those ffmpeg include dirs.

### CODE REVIEW

**Review by skrax — COMMENTED** [review]
Typo in ln 151

Did you recompile your code?

**Comment by natewind** [comment]
> Typo in ln 151

Fixed.

> Did you recompile your code?

No, as I said, I don’t have some necessary libraries. I’ll try installing them again later.
Although I thought there was some CI/CD thingie here when I was sending the previous merge request...

**Comment by skrax** [comment]
Oh, I see. 
I don't know what happened to the CI, but I guess that can be fixed.

**Comment by gynt** [comment]
@natewind The build failed: https://github.com/sourcehold/Sourcehold/actions/runs/545742597

I could either unmerge this pull request and you can make a fix, or we open a new PR for this. I do not have a preference.

**Comment by natewind** [comment]
Probably better to unmerge for a fix.

**Comment by gynt** [comment]
I reverted this PR and you can now submit a new PR from your fork with the corrected changes. I think if you check out the master branch, you will also have CI building on your branch, so you can immediately verify whether it builds.

**Pull request merged**
